lang: pt

project:
  output-dir: docs/pt

website:
  navbar:
    left:
      - href: /index.html
        text: "**PT**"
      - href: ../en/index.html
        text: EN  
      - href: ../index.html
        text: ES      
      - text: "Página inicial"
        href: /index.html
      - text: Sobre a LatinR
        menu:        
          - text: "Equipe organizadora"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/apoio.qmd
          - href: sobre/coc/codigo-de-conduta.qmd
          - href: sobre/ediciones-anteriores/edicoes-anteriores.qmd     
      - text: Participe
        menu: 
          - text: "Chamada para submissão de trabalhos"
            href: blog/pt/2023-04-24-submissao-de-trabalhos-2023.html
          - text: "Inscrição"
            href: https://www.eventbrite.cl/e/latinr-2023-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-637517701607
          - text: "Preços de inscrição"
            href: blog/pt/2023-06-08-inscriptionpt.html          
      - text: LatinR 2023
        menu: 
          - text: "Localização"
            href: cronograma/lugar/lugar-pt.qmd    
          - text: "Recursos turísticos"
            href: cronograma/recursos-turisticos/index-pt.qmd  
          - text: "Bolsas"
            href: blog/pt/2023-08-18-bolsas-2023.html    
      - text: Programa
        menu: 
          - text: "Programa resumido"
            href: cronograma/programa/preliminar.qmd 
          - text: "Palestras convidadas"
            href: cronograma/conferencistas/palestras-convidadas.qmd    
          - text: "Workshops"
            href: cronograma/tutoriales/workshops-pt.qmd                 
          - text: "Apresentações"
            href: cronograma/programa/presentaciones.qmd 
          - text: "Pôsters"
            href: cronograma/programa/posters.qmd               
      - text: "Novidades"
        href: blog/pt/index.html                 
      
        