project:
  type: website
  preview: 
    port: 4200  

website:
  title: "LatinR 2023"
  sidebar: false
  navbar:
    pinned: false
    logo: "img/logo.png"
    logo-alt: "Latin-R logo"
    title: false
    background: "#ffffff"
    foreground: "#737373"
    search: true
  page-footer: 
#    left: "Proudly supported by R Consortium"
    center: "Copyright Â© 2023, LatinR Team" 
    right: 
      - icon: envelope
        aria-label: "Email"
        href: mailto:latinr.conf@gmail.com   
      - icon: github
        href: https://github.com/latinr
      - icon: twitter 
        href: https://twitter.com/LatinR_Conf     
        aria-label: "Twitter"
      - icon: linkedin
        href: https://www.linkedin.com/company/latinrconf/
        aria-label: "Linkedin"
      - icon: slack
        href: https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc
        aria-label: "Slack"

      
profile:
  default: es
  group: 
    - [en, es, pt]

format:
  html:
    theme: styles.scss
    toc: false
    page-layout: full
